name: Daily Script

on:
  schedule:
    - cron: '0 23 * * *'  # Esegue ogni giorno alle 23:00 UTC
  workflow_dispatch:       # Permette di eseguire manualmente

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install twilio requests

      - name: Run script
        env:
          api_key: ${{ secrets.api_key }}
          account_sid: ${{ secrets.account_sid }}
          auth_token: ${{ secrets.auth_token }}
        run: python main.py
